server:
  port: 8080
  servlet:
    context-path: /finance-service
spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true