server:
  port: 2001
  servlet:
    context-path: /community-service
spring:
  application:
    name: community-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/community_finance

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: 9092

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/