server:
  port: 8081
spring:
  application:
    name: community-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/community_finance
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/