server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: finance_service
          uri: http://localhost:8080
          predicates:
            - Path=/finance-service/**
        - id: user_service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
        - id: community_service
          uri: http://localhost:8082
          predicates:
            - Path=/community-service/**
        - id: community_service_ws
          uri: ws://localhost:8082
          predicates:
              - Path=/community-service/ws/**


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    finance-service:
#      path: /api/finance/**
#      serviceId: finance-service
#    community-service:
#      path: /api/community/**
#      serviceId: community-service
