

services:
  # MySQL cho Finance Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # MongoDB cho Community Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Finance Service
  finance-service:
    build: ./finance-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  # Community Service
  community-service:
    build: ./community-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data: