services:
  # MySQL cho Finance Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # MongoDB cho Community Service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # Finance Service
  finance-service:
    build: ./finance-service
    ports:
      - "2000:2000"
    depends_on:
      - mysql
    networks:
      - app-network

  # Community Service
  community-service:
    build: ./community-service
    ports:
      - "2001:2001"
    depends_on:
      - mongodb
    networks:
      - app-network
  # user Service
  user-service:
    build: ./user-service
    ports:
      - "2002:2002"
    depends_on:
      - mysql
    networks:
      - app-network
  # notification Service
  notification-service:
    build: ./notification-service
    ports:
      - "2003:2003"
    depends_on:
      - mongodb
    networks:
      - app-network
  #  kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# #####
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  mongo-data: